<?php

require_once __DIR__ . "/../vendor/autoload.php";
require_once __DIR__ . "/../../AssessmentTest/vendor/autoload.php";

use ILIAS\DI\Container;
use srag\asq\Application\Service\ASQDIC;
use srag\asq\Infrastructure\Setup\lang\SetupAsqLanguages;
use srag\asq\Infrastructure\Setup\sql\SetupDatabase;
use srag\asq\QuestionPool\Domain\Model\QuestionPoolListItem;
use srag\asq\QuestionPool\Infrastructure\Setup\lang\SetupAsqPoolLanguages;
use srag\asq\QuestionPool\Infrastructure\Setup\sql\SetupAsqPoolDatabase;
use srag\CustomInputGUIs\AsqQuestionPool\Loader\CustomInputGUIsLoaderDetector;
use srag\Plugins\AsqQuestionPool\Utils\AsqQuestionPoolTrait;
use srag\RemovePluginDataConfirm\AsqQuestionPool\RepositoryObjectPluginUninstallTrait;
use srag\asq\QuestionPool\Domain\Persistence\QuestionPoolEventStoreAr;

/**
 * Class ilAsqQuestionPoolPlugin
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @author studer + raimann ag - Team Custom 2 <support-custom2@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilAsqQuestionPoolPlugin extends ilRepositoryObjectPlugin
{

    use RepositoryObjectPluginUninstallTrait;
    use AsqQuestionPoolTrait;

    const PLUGIN_CLASS_NAME = self::class;
    const PLUGIN_ID = "xaqp";
    const PLUGIN_NAME = "AsqQuestionPool";
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * ilAsqQuestionPoolPlugin constructor
     */
    public function __construct()
    {
        parent::__construct();
    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @inheritDoc
     */
    public function exchangeUIRendererAfterInitialization(Container $dic) : Closure
    {
        return CustomInputGUIsLoaderDetector::exchangeUIRendererAfterInitialization();
    }


    /**
     * @inheritDoc
     */
    public function getPluginName() : string
    {
        return self::PLUGIN_NAME;
    }


    /**
     * @inheritDoc
     */
    public function updateLanguages(/*?array*/ $a_lang_keys = null) : void
    {
        parent::updateLanguages($a_lang_keys);

        $this->installRemovePluginDataConfirmLanguages();
    }


    /**
     * @inheritDoc
     */
    protected function deleteData() : void
    {
        global $DIC;

        ASQDIC::initiateASQ($DIC);

        SetupAsqPoolDatabase::uninstall();

        self::asqQuestionPool()->dropTables();
    }

    /**
     * @inheritDoc
     */
    protected function afterActivation()
    {
        global $DIC;

        ASQDIC::initiateASQ($DIC);

        SetupAsqPoolDatabase::run();
        SetupAsqPoolLanguages::new()->run();
    }

    protected function afterDeactivation()
    {
        global $DIC;

        ASQDIC::initiateASQ($DIC);

        SetupAsqPoolDatabase::uninstall();
    }

    /**
     * @inheritDoc
     */
    protected function shouldUseOneUpdateStepOnly() : bool
    {
        return false;
    }
}
