<?php

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\AsqQuestionPool\Config\ConfigCtrl;
use srag\Plugins\AsqQuestionPool\Utils\AsqQuestionPoolTrait;
use srag\DevTools\AsqQuestionPool\DevToolsCtrl;
use srag\DIC\AsqQuestionPool\DICTrait;

/**
 * Class ilAsqQuestionPoolConfigGUI
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @author studer + raimann ag - Team Custom 2 <support-custom2@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilAsqQuestionPoolConfigGUI extends ilPluginConfigGUI
{

    use DICTrait;
    use AsqQuestionPoolTrait;

    const CMD_CONFIGURE = "configure";
    const PLUGIN_CLASS_NAME = ilAsqQuestionPoolPlugin::class;


    /**
     * ilAsqQuestionPoolConfigGUI constructor
     */
    public function __construct()
    {

    }


    /**
     * @inheritDoc
     */
    public function performCommand(/*string*/ $cmd) : void
    {
        $this->setTabs();

        $next_class = self::dic()->ctrl()->getNextClass($this);

        switch (strtolower($next_class)) {
            case strtolower(ConfigCtrl::class):
                self::dic()->ctrl()->forwardCommand(new ConfigCtrl());
                break;

            default:
                $cmd = self::dic()->ctrl()->getCmd();

                switch ($cmd) {
                    case self::CMD_CONFIGURE:
                        $this->{$cmd}();
                        break;

                    default:
                        break;
                }
                break;
        }
    }


    /**
     *
     */
    protected function configure() : void
    {
        self::dic()->ctrl()->redirectByClass(ConfigCtrl::class, ConfigCtrl::CMD_CONFIGURE);
    }


    /**
     *
     */
    protected function setTabs() : void
    {
        ConfigCtrl::addTabs();

        self::dic()->locator()->addItem(ilAsqQuestionPoolPlugin::PLUGIN_NAME, self::dic()->ctrl()->getLinkTarget($this, self::CMD_CONFIGURE));
    }
}
