<?php

use srag\Plugins\AsqQuestionPool\AsqQuestionPoolTrait;
use srag\Plugins\AsqQuestionPool\ObjectSettings\ObjectSettings;
use srag\DIC\AsqQuestionPool\DICTrait;

/**
 * Class ilObjAsqQuestionPool
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @author studer + raimann ag - Team Custom 2 <support-custom2@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilObjAsqQuestionPool extends ilObjectPlugin
{

    use DICTrait;
    use AsqQuestionPoolTrait;

    const PLUGIN_CLASS_NAME = ilAsqQuestionPoolPlugin::class;
    /**
     * @var ObjectSettings|null
     */
    protected $object_settings = null;


    /**
     * ilObjAsqQuestionPool constructor
     *
     * @param int $a_ref_id
     */
    public function __construct(/*int*/ $a_ref_id = 0)
    {
        parent::__construct($a_ref_id);
    }


    /**
     * @inheritDoc
     */
    public function doCreate() : void
    {
        $this->object_settings = self::asqQuestionPool()->objectSettings()->factory()->newInstance();

        $this->object_settings->setObjId($this->id);

        self::asqQuestionPool()->objectSettings()->storeObjectSettings($this->object_settings);
    }


    /**
     * @inheritDoc
     */
    public function doDelete() : void
    {
        if ($this->object_settings !== null) {
            self::asqQuestionPool()->objectSettings()->deleteObjectSettings($this->object_settings);
        }
    }


    /**
     * @inheritDoc
     */
    public function doRead() : void
    {
        $this->object_settings = self::asqQuestionPool()->objectSettings()->getObjectSettingsById(intval($this->id));
    }


    /**
     * @inheritDoc
     */
    public function doUpdate() : void
    {
        self::asqQuestionPool()->objectSettings()->storeObjectSettings($this->object_settings);
    }


    /**
     * @inheritDoc
     */
    public final function initType() : void
    {
        $this->setType(ilAsqQuestionPoolPlugin::PLUGIN_ID);
    }


    /**
     * @return bool
     */
    public function isOnline() : bool
    {
        return $this->object_settings->isOnline();
    }


    /**
     * @param bool $is_online
     */
    public function setOnline(bool $is_online = true) : void
    {
        $this->object_settings->setOnline($is_online);
    }

    /**
     * @return string
     */
    public function getData() : ?string
    {
        return $this->object_settings->getData();
    }

    /**
     * @param string $data
     */
    public function setData(string $data)
    {
        $this->object_settings->setData($data);
    }

    /**
     * @inheritDoc
     *
     * @param ilObjAsqQuestionPool $new_obj
     */
    protected function doCloneObject(/*ilObjAsqQuestionPool*/ $new_obj, /*int*/ $a_target_id, /*?int*/ $a_copy_id = null) : void
    {
        $new_obj->object_settings = self::asqQuestionPool()->objectSettings()->cloneObjectSettings($this->object_settings);

        $new_obj->object_settings->setObjId($new_obj->id);

        self::asqQuestionPool()->objectSettings()->storeObjectSettings($new_obj->object_settings);
    }
}
