<?php

namespace srag\Plugins\AsqQuestionPool\Utils;

use srag\Plugins\AsqQuestionPool\Repository;

/**
 * Trait AsqQuestionPoolTrait
 *
 * Generated by SrPluginGenerator v2.8.1
 *
 * @package srag\Plugins\AsqQuestionPool\Utils
 *
 * @author studer + raimann ag - Team Custom 2 <support-custom2@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
trait AsqQuestionPoolTrait
{

    /**
     * @return Repository
     */
    protected static function asqQuestionPool() : Repository
    {
        return Repository::getInstance();
    }
}
